# Generated by Django 2.2.7 on 2019-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0002_remove_shorturlmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
